//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_editTransections
    {
        public int idTrans { get; set; }
        public int idPayment { get; set; }
        public int value { get; set; }
        public int Date { get; set; }
        public bool isOrg { get; set; }
        public string Des { get; set; }
    }
}
