//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_registrationCourses
    {
        public int idRegcourse { get; set; }
        public string title { get; set; }
        public int idYear { get; set; }
        public int value { get; set; }
        public int startDateTime { get; set; }
        public int endDateTime { get; set; }
        public string des { get; set; }
    }
}
