//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_classes
    {
        public int idClass { get; set; }
        public string className { get; set; }
        public Nullable<int> classCapacity { get; set; }
        public int idLevel { get; set; }
        public int idYear { get; set; }
        public int idMajor { get; set; }
    }
}
