//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_exams
    {
        public int idExam { get; set; }
        public int idExamType { get; set; }
        public int idLesson { get; set; }
        public int idClass { get; set; }
        public int idTerm { get; set; }
        public int idTeacher { get; set; }
        public string examTitle { get; set; }
        public int examDate { get; set; }
        public Nullable<int> maxScore { get; set; }
        public string des { get; set; }
    }
}
