//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_studentsData
    {
        public int idStudData { get; set; }
        public int idStudent { get; set; }
        public int idYear { get; set; }
        public short idType { get; set; }
        public string dataTitle { get; set; }
        public Nullable<int> dataDate { get; set; }
        public string dataFile { get; set; }
        public string des { get; set; }
    }
}
