//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_years
    {
        public int idYear { get; set; }
        public string yearName { get; set; }
        public Nullable<int> yearStart { get; set; }
        public Nullable<int> yearEnd { get; set; }
        public string des { get; set; }
    }
}
