//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Avrages
    {
        public int id { get; set; }
        public int idYear { get; set; }
        public int idMonth { get; set; }
        public int idClass { get; set; }
        public int idLesson { get; set; }
        public int idStudent { get; set; }
        public int idDesScore { get; set; }
        public double Score { get; set; }
    }
}
