//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Setting
    {
        public int idSetting { get; set; }
        public string schoolName { get; set; }
        public string manager { get; set; }
        public int smsCount { get; set; }
        public double Version { get; set; }
        public string teacherVersion { get; set; }
        public string Website { get; set; }
        public string azmoonWebsite { get; set; }
    }
}
