//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_majors
    {
        public int idMajor { get; set; }
        public Nullable<int> unitCount { get; set; }
        public Nullable<int> majorCode { get; set; }
        public string majorName { get; set; }
    }
}
