//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_absentation
    {
        public int idAbsentation { get; set; }
        public int idStudent { get; set; }
        public int idDataTable { get; set; }
        public bool status { get; set; }
        public int date { get; set; }
    }
}
