//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_scores
    {
        public int idScore { get; set; }
        public int idStudent { get; set; }
        public int idExam { get; set; }
        public int date { get; set; }
        public int idDescriptiveScore { get; set; }
        public double score { get; set; }
        public string des { get; set; }
    }
}
