//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_students
    {
        public int idStudent { get; set; }
        public int studentCode { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string fatherName { get; set; }
        public bool gender { get; set; }
        public long birthDate { get; set; }
        public int idStatus { get; set; }
        public string natCode { get; set; }
        public string homePhone { get; set; }
        public string imgPersonal { get; set; }
        public string imgManifest { get; set; }
        public bool leftHand { get; set; }
        public string homeAddress { get; set; }
        public string studentMobile { get; set; }
        public int idMarrige { get; set; }
        public string religion { get; set; }
        public bool isActive { get; set; }
        public string studUser { get; set; }
        public string pass { get; set; }
        public string pUser { get; set; }
        public string pPass { get; set; }
        public Nullable<int> idFatherEdu { get; set; }
        public string fJob { get; set; }
        public string fJobAddress { get; set; }
        public string fJobPhone { get; set; }
        public string fPhone { get; set; }
        public string motherName { get; set; }
        public Nullable<int> idMotherEdu { get; set; }
        public string mJob { get; set; }
        public string mJobAddress { get; set; }
        public string mJobPhone { get; set; }
        public string mPhone { get; set; }
    }
}
