//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_messageRecord
    {
        public int idMsgRecord { get; set; }
        public int idMessage { get; set; }
        public int idReceiverType { get; set; }
        public int idReceiver { get; set; }
        public Nullable<bool> isRead { get; set; }
        public int idYear { get; set; }
        public Nullable<bool> isActiveSend { get; set; }
        public Nullable<bool> isActiveRecive { get; set; }
    }
}
