//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payments
    {
        public int idPay { get; set; }
        public int idStud { get; set; }
        public short idPayType { get; set; }
        public int idYear { get; set; }
        public int value { get; set; }
        public string issuTracking { get; set; }
        public Nullable<int> cashDate { get; set; }
        public Nullable<int> cardDate { get; set; }
        public Nullable<int> chDate { get; set; }
        public Nullable<int> chNumber { get; set; }
        public string chBank { get; set; }
        public string fishNumber { get; set; }
        public Nullable<int> fishDate { get; set; }
        public int financialDate { get; set; }
        public int docNo { get; set; }
        public bool isOrg { get; set; }
        public string Des { get; set; }
    }
}
