//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SiteContent
    {
        public int id { get; set; }
        public string Content { get; set; }
        public string Tell1 { get; set; }
        public string Tell2 { get; set; }
        public string Address { get; set; }
        public string Logo { get; set; }
        public string backImg { get; set; }
    }
}
