//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_offices
    {
        public int idOffices { get; set; }
        public bool status { get; set; }
        public int personalCode { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string fatherName { get; set; }
        public bool gender { get; set; }
        public int birthDate { get; set; }
        public string natCode { get; set; }
        public string imgManifest { get; set; }
        public string imgPersonal { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string userName { get; set; }
        public string Pass { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string job { get; set; }
    }
}
