//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_news
    {
        public int id { get; set; }
        public string title { get; set; }
        public string body { get; set; }
        public int date { get; set; }
        public int receiverType { get; set; }
        public int visitCount { get; set; }
    }
}
