//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_answers
    {
        public int id { get; set; }
        public int idUser { get; set; }
        public int userType { get; set; }
        public int idRef { get; set; }
        public int userAnswer { get; set; }
    }
}
