//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_debts
    {
        public int idDebt { get; set; }
        public int idStud { get; set; }
        public int idYear { get; set; }
        public Nullable<int> idCost { get; set; }
        public Nullable<int> idRegCourse { get; set; }
        public int Date { get; set; }
    }
}
