//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_discipline
    {
        public int idStudentDisciplines { get; set; }
        public string disName { get; set; }
        public int idStudent { get; set; }
        public int idClass { get; set; }
        public int actDate { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string des { get; set; }
        public int idYear { get; set; }
        public int idTerm { get; set; }
    }
}
