//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_homeWork
    {
        public int idClass { get; set; }
        public string className { get; set; }
        public int idHomeWork { get; set; }
        public string title { get; set; }
        public string body { get; set; }
        public string HomeWorkFile { get; set; }
        public string answerBody { get; set; }
        public string answerFile { get; set; }
        public int exDateTime { get; set; }
        public int UploadDate { get; set; }
        public int idYear { get; set; }
        public int idTeacher { get; set; }
        public int idLesson { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
    }
}
