//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_studentScore
    {
        public int idScore { get; set; }
        public int idStudent { get; set; }
        public int date { get; set; }
        public double score { get; set; }
        public int idDescriptiveScore { get; set; }
        public string lessonName { get; set; }
        public Nullable<int> maxScore { get; set; }
        public string examType { get; set; }
        public string des { get; set; }
        public int idYear { get; set; }
        public string desScore { get; set; }
        public int idExam { get; set; }
        public Nullable<int> numScore { get; set; }
        public int idLesson { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
    }
}
