//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_teacherSchedule
    {
        public int idDataTable { get; set; }
        public int idDay { get; set; }
        public int idBell { get; set; }
        public int idYear { get; set; }
        public int idClass { get; set; }
        public string className { get; set; }
        public string lessonName { get; set; }
        public int idTeacher { get; set; }
        public int idLesson { get; set; }
        public Nullable<int> idTeacher2 { get; set; }
        public Nullable<int> idLesson2 { get; set; }
        public int idLevel { get; set; }
    }
}
